### ISSUE TITLE
php_PDO_Informix not found in php7.2

### ISSUE THREAD

**Issue by WookPlay** [stephane303/php_pdo_informix-1.3.3-7.1-vc14-x86#1]
hello, I'm loading the extension but in php7.2 it does not work.

**Comment by stephane303** [comment]
it's because it has been compiled for version 7.1 only, i do not have the environnement to compile it for 7.2, you will have to compile it yourself. You will find the instructions in the [README.md](https://github.com/stephane303/php_pdo_informix-1.3.3-7.1-vc14-x86/blob/master/README.md)
